# Cargo build configuration for cross-platform compatibility

# Windows: Use baseline x86-64 instructions for maximum compatibility
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=x86-64"]

# macOS: Use Apple M1 baseline (compatible with all Apple Silicon)
[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=apple-m1"]
